#lang scheme
;;Problem: Each of the following two procedures defines a method for adding two positive integers in
;;  terms of the procedures inc, which increments its argument by 1, and dec, which decrements its
;;   agument by 1.

;;Using the substitution model, illustrate the process generated by each procedure in evaluating (+ 4 5).
;;Are these processes iterative or recursive?

;;Procedure 1
(define (+ a b)
  (if (= a 0)
      b
      (inc (+ (dec a) b))))
;;Outputs 5
;;Recursive Porcess (U-shape)
;(+ 4 5)
;(inc (+ 3 5))
;(inc (inc (+ 2 5)))
;(inc (inc (inc (+ 1 5))))
;(inc (inc (inc (inc (+ 0 5)))))
;(inc (inc (inc (inc 5))))
;(inc (inc (inc 6)))
;(inc (inc 7))
;(inc 8)
;9

(define (+ a b)
  (if (= a 0)
      b
      (+ (dec a) (inc b))))
;;Outputs 9
;;Iterative Process (linear even column)
;(+ 4 5)
;(+ 3 6)
;(+ 2 7)
;(+ 1 8)
;(+ 0 9)
;9